name: Jekyll site CI

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v /home/runner/work/feelresponsive.io/feelresponsive.io:/srv/jekyll \
        -v /home/runner/work/feelresponsive.io/feelresponsive.io/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future --trace"

